added CI checks for GITLAB CI CATALOG Essentials

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,12 +1,61 @@
+include:
+  - component: $CI_SERVER_FQDN/$CI_PROJECT_PATH/scan@$CI_COMMIT_SHA
+
+stages: [test, release]
+
+variables:
+  # make sure its same as the job name in the template/scan.yml
+  SCAN_JOB_NAME: "vet_dependency_scanning"
+
+# Ensure that are able to load (import) the component
+ensure-job-added:
+  stage: test
+  image: badouralix/curl-jq
+  script:
+    - echo "Expect that a job named '$SCAN_JOB_NAME' is added to the pipeline"
+    - |
+      route="$CI_API_V4_URL/projects/$CI_PROJECT_ID/pipelines/$CI_PIPELINE_ID/jobs"
+      count=`curl --silent $route | jq 'map(select(.name | contains("$SCAN_JOB_NAME"))) | length'`
+      if [ "$count" != "1" ]; then
+        echo "Job named '$SCAN_JOB_NAME' not found in pipeline"
+        exit 1
+      fi
+  rules:
+    - if: ($CI_COMMIT_BRANCH || $CI_COMMIT_TAG) && $CI_SERVER_HOST =~ /gitlab.com/
+
+# Ensure that a project description exists, because it will be important to display
+# the resource in the catalog.
+check-description:
+  image: badouralix/curl-jq
+  script:
+    - |
+      route="$CI_API_V4_URL/projects/$CI_PROJECT_ID"
+      desc=`curl --silent $route | jq '.description'`
+      if [ "$desc" = "null" ]; then
+        echo "Description not set. Please set a projet description"
+        exit 1
+      else
+        echo "Description set"
+      fi
+  rules:
+    - if: $CI_SERVER_HOST =~ /gitlab.com/
+
+
+# Ensure that a `README.md` exists in the root directory as it represents the
+# documentation for the whole components repository.
+check-readme:
+  image: busybox
+  script: ls README.md || (echo "Please add a README.md file" && exit 1)
+
+
 # Rlease is Required (specialy `release` keyword) for publishing CI Component To CI / CD Catalog
 # See: https://docs.gitlab.com/ci/components/#publish-a-new-release
-#
-# create-release:
-#   stage: release
-#   image: registry.gitlab.com/gitlab-org/release-cli:latest
-#   script: echo "Creating release $CI_COMMIT_TAG"
-#   rules:
-#     - if: $CI_COMMIT_TAG
-#   release:
-#     tag_name: $CI_COMMIT_TAG
-#     description: "Release $CI_COMMIT_TAG of components repository $CI_PROJECT_PATH"
+create-release:
+  stage: release
+  image: registry.gitlab.com/gitlab-org/release-cli:latest
+  script: echo "Creating release $CI_COMMIT_TAG"
+  rules:
+    - if: $CI_COMMIT_TAG
+  release:
+    tag_name: $CI_COMMIT_TAG
+    description: "Release $CI_COMMIT_TAG of components repository $CI_PROJECT_PATH"
