fix: ci

diff --git a/templates/scan.yml b/templates/scan.yml
--- a/templates/scan.yml
+++ b/templates/scan.yml
@@ -57,32 +57,35 @@ spec:
       default: true
 ---
 
-# For inputs files, check if they exist if input is provided
-.ensure-input-file-exists: &ensure-input-file-exists |
-  echo "Checking if file exists: $INPUT_FILE_VARIABLE"
+# If policy file is provided, check if it exists
+.check-policy-file: &check-policy-file | 
+  echo "Checking if policy file exists: $[[ inputs.policy ]]"
 
-  if [ ! -z "$INPUT_FILE_VARIABLE" ]; then
-    echo "Checking file: $INPUT_FILE_VARIABLE"
+  if [ ! -z "$[[ inputs.policy ]]" ]; then
+    echo "Checking file: $[[ inputs.policy ]]"
 
-    if [ ! -f "$INPUT_FILE_VARIABLE" ]; then
-      echo "File not found: $INPUT_FILE_VARIABLE"
+    if [ ! -f "$[[ inputs.policy ]]" ]; then
+      echo "File not found: $[[ inputs.policy ]]"
       exit 1
     fi
 
-    echo "File found"
+    echo "Policy file found"
   fi
 
-# If policy file is provided, check if it exists
-.check-policy-file: &check-policy-file 
-  <<: *ensure-input-file-exists
-  variables:
-    INPUT_FILE_VARIABLE: $[[ inputs.policy ]]
-
 # If exception file is provided, check if it exists
-.check-exception-file: &check-exception-file 
-  <<: *ensure-input-file-exists
-  variables:
-    INPUT_FILE_VARIABLE: $[[ inputs.exception-file ]]
+.check-exception-file: &check-exception-file |
+  echo "Checking if exception file exists: $[[ inputs.exception-file ]]"
+
+  if [ ! -z "$[[ inputs.exception-file ]]" ]; then
+    echo "Checking file: $[[ inputs.exception-file ]]"
+
+    if [ ! -f "$[[ inputs.exception-file ]]" ]; then
+      echo "File not found: $[[ inputs.exception-file ]]"
+      exit 1
+    fi
+
+    echo "Exception file found"
+  fi
 
 # We need curl and jq to check for lockfile changes in merge request pipelines
 .download-curl-jq: &download-curl-jq |
