working

diff --git a/templates/scan.yml b/templates/scan.yml
--- a/templates/scan.yml
+++ b/templates/scan.yml
@@ -9,8 +9,7 @@ spec:
     policy:
       description: 'Path to policy file, default policy will be used when not given'
       type: string 
-      default: '.gitlab/vet/policy.yml' # For now we don't want to use a default policy, since we are using sarif then sarif-converter which will use the default policy
-      # later when we have our own gitlab-specific-report, then we can make this default to '.gitlab/vet/policy.yml', and optional
+      default: '.gitlab/vet/policy.yml'
     version: 
       description: 'vet version to use for the scan. Defaults to using latest release'
       type: string
@@ -57,6 +56,18 @@ spec:
       type: boolean
       default: true
 ---
+# For now policy file is required, but in future we can make it optional
+# Since we are generating sarif report
+.check-policy-file: &check-policy-file |
+  if [ ! -f $[[ inputs.policy ]] ]; then
+    echo "Policy file not found: $[[ inputs.policy ]]"
+    exit 1
+  fi
+
+# Download sarif-converter for converting sarif report to gitlab specific dependency scanning report 
+.download-sarif-converter: &download-sarif-converter |
+  wget -O sarif-converter https://gitlab.com/ignis-build/sarif-converter/-/releases/permalink/latest/downloads/bin/sarif-converter-linux
+  chmod +x sarif-converter
 
 vet_dependency_scanning:
   stage: $[[ inputs.stage ]]
@@ -66,14 +77,21 @@ vet_dependency_scanning:
     entrypoint: [""] # by default vet's docker entrypoint is ["vet"] but we want to it as environment  / shell, so we override it to empty allowsing gitlab to work with it
   before_script:
     # Download sarif-converter for converting sarif report to gitlab specific dependency scanning report
-    # - wget -O sarif-converter https://gitlab.com/ignis-build/sarif-converter/-/releases/permalink/latest/downloads/bin/sarif-converter-linux
-    # - chmod +x sarif-converter
+    - *check-policy-file
+    # - *download-sarif-converter
   variables:
     ARTIFACT_FILENAME: "gl-dependency-scanning-report.json"
   script:
     - vet version
+    - whoami
+    - pwd
+    - ls -la
+    # - vet scan --policy $[[ inputs.policy ]] --output $ARTIFACT_FILENAME
+    # - ./sarif-converter --input $ARTIFACT_FILENAME --output $ARTIFACT_FILENAME
+    # - cat $ARTIFACT_FILENAME
   artifacts:
     access: $[[ inputs.artifact_access ]]
     reports: # This is required for Security Scanning
       dependency_scanning: $ARTIFACT_FILENAME
     expire_in: 1 week
+
